package com.rights.helper.controller;
import com.rights.helper.model.*; import com.rights.helper.repository.*; import jakarta.servlet.http.HttpSession; import org.springframework.data.domain.PageRequest; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/posts") public class PostController {
 final PostRepository posts; final UserRepository users; final CommentRepository comments; final PostLikeRepository likes;
 PostController(PostRepository p,UserRepository u,CommentRepository c,PostLikeRepository l){posts=p;users=u;comments=c;likes=l;}
 @GetMapping public Map<String,Object> list(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="")String category){var pg=posts.findAllByOrderByCreateTimeDesc(PageRequest.of(Math.max(page,0),Math.min(size,50)));List<Map<String,Object>> data=new ArrayList<>();for(Post x:pg)if(category.isBlank()||x.category.equals(category))data.add(view(x));return Map.of("items",data,"total",pg.getTotalElements(),"page",page,"size",size);}
 @GetMapping("/{id}") public ResponseEntity<?> detail(@PathVariable Long id){return posts.findById(id).map(p->{Map<String,Object>v=view(p);v.put("comments",comments.findByPostIdOrderByCreateTimeAsc(id).stream().map(this::commentView).toList());return ResponseEntity.ok(v);}).orElse(ResponseEntity.notFound().build());}
 @PostMapping public ResponseEntity<?> create(@RequestBody Map<String,Object>b,HttpSession s){User u=current(s);if(u==null)return unauthorized();String title=String.valueOf(b.getOrDefault("title","")).trim(),content=String.valueOf(b.getOrDefault("content","")).trim(),cat=String.valueOf(b.getOrDefault("category","其他问题"));boolean anon=Boolean.parseBoolean(String.valueOf(b.getOrDefault("anonymous",false)));if(title.isBlank()||content.isBlank())return ResponseEntity.badRequest().body(Map.of("message","标题和内容不能为空"));Post p=new Post();p.user=u;p.title=title;p.content=content;p.category=cat;p.anonymous=anon;posts.save(p);return ResponseEntity.ok(view(p));}
 @PostMapping("/{id}/comments") public ResponseEntity<?> comment(@PathVariable Long id,@RequestBody Map<String,String>b,HttpSession s){User u=current(s);if(u==null)return unauthorized();Post p=posts.findById(id).orElse(null);if(p==null)return ResponseEntity.notFound().build();String c=b.getOrDefault("content","").trim();if(c.isBlank())return ResponseEntity.badRequest().body(Map.of("message","回复不能为空"));Comment x=new Comment();x.post=p;x.user=u;x.content=c;comments.save(x);p.commentCount++;posts.save(p);return ResponseEntity.ok(commentView(x));}
 @PostMapping("/{id}/like") public ResponseEntity<?> like(@PathVariable Long id,HttpSession s){User u=current(s);if(u==null)return unauthorized();Post p=posts.findById(id).orElse(null);if(p==null)return ResponseEntity.notFound().build();var old=likes.findByPostIdAndUserId(id,u.id);if(old.isPresent()){likes.delete(old.get());p.likeCount=Math.max(0,p.likeCount-1);}else{PostLike x=new PostLike();x.post=p;x.user=u;likes.save(x);p.likeCount++;}posts.save(p);return ResponseEntity.ok(Map.of("likeCount",p.likeCount,"liked",likes.findByPostIdAndUserId(id,u.id).isPresent()));}
 @DeleteMapping("/{id}") public ResponseEntity<?> delete(@PathVariable Long id,HttpSession s){User u=current(s);if(u==null)return unauthorized();Post p=posts.findById(id).orElse(null);if(p==null)return ResponseEntity.notFound().build();if(!p.user.id.equals(u.id))return ResponseEntity.status(403).body(Map.of("message","只能删除自己的帖子"));comments.findByPostIdOrderByCreateTimeAsc(id).forEach(comments::delete);posts.delete(p);return ResponseEntity.ok(Map.of("message","已删除"));}
 @PostMapping("/{id}/report") public ResponseEntity<?> report(@PathVariable Long id,HttpSession s){User u=current(s);if(u==null)return unauthorized();Post p=posts.findById(id).orElse(null);if(p==null)return ResponseEntity.notFound().build();p.reportCount++;posts.save(p);return ResponseEntity.ok(Map.of("message","感谢反馈，我们会核查该内容"));}
 private User current(HttpSession s){Object id=s.getAttribute("userId");return id==null?null:users.findById((Long)id).orElse(null);} private ResponseEntity<?> unauthorized(){return ResponseEntity.status(401).body(Map.of("message","请先登录"));}
 private Map<String,Object> view(Post p){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.id);m.put("title",p.title);m.put("content",p.content);m.put("category",p.category);m.put("anonymous",p.anonymous);m.put("author",p.anonymous?"匿名用户":p.user.nickname);m.put("userId",p.user.id);m.put("likeCount",p.likeCount);m.put("commentCount",p.commentCount);m.put("createTime",p.createTime);return m;}
 private Map<String,Object> commentView(Comment c){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.id);m.put("author",c.user.nickname);m.put("content",c.content);m.put("createTime",c.createTime);return m;}
}
